### ISSUE TITLE
tensor_try error

### ISSUE THREAD

**Issue by shreyas987** [Tanny16/Tensor-based-eLSTM#1]
When i run test.py i am getting the following error.

Using TensorFlow backend.
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    from utils import GetData
  File "../utils/GetData.py", line 6, in <module>
    import utils.tensor_try as tensor_tucker

tensor_try does not seem to exist.
Am i missing something?
Can you please help

**Comment by zhangzhangyameng** [comment]
Hello, did you get the "tensor_try" file?

**Comment by fatima-dakalbab** [comment]
Hello, did anyone get "tensor_try" file?
